# Generated by Django 5.1.2 on 2024-11-25 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_author_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
