# Generated by Django 5.1.2 on 2024-11-28 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0008_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='upload_date',
        ),
        migrations.AlterField(
            model_name='image',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blogapp.post'),
        ),
    ]
