name: Django CI with AVTest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      redis:
        image: redis
        ports:
          - 6379:6379
        options: --health-cmd "redis-cli ping" --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          gcc \
          python3-dev \
          libffi-dev \
          libssl-dev \
          ffmpeg \
          chromium-browser \
          chromium-chromedriver \
          bsdtar

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install beautifulsoup4  # Для тестов Post_test.py

    - name: Run migrations
      run: python manage.py migrate

    - name: Run Django tests
      run: python manage.py test

    - name: Build Docker image
      run: docker build -t django-blogapp .

    - name: Run Django container
      run: |
        docker run -d -p 8000:8000 --name django-app django-blogapp
        sleep 15  # Wait for Django to start
        docker ps -a
        curl -v http://localhost:8000/healthcheck/

    - name: Setup and run AVTest
      run: |
        # Clone AVTest repository
        git clone https://github.com/screemf/avtest.git
        cd avtest
        
        # Install test dependencies
        pip install \
          opencv-python \
          numpy \
          pillow \
          pytest \
          pytest-xdist \
          requests \
          selenium \
          webdriver-manager \
          beautifulsoup4 \
          allure-pytest
        
        # Install Allure CLI
        wget https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.tgz
        bsdtar -xzf allure-2.27.0.tgz -C /usr/local --strip-components=1
        echo "/usr/local/bin" >> $GITHUB_PATH
        
        # Go to tests directory
        cd Test
        
        # Debug: Show test files
        echo "Test files available:"
        ls -la
        
        # Run test groups with WebDriver Manager
        echo "Running test suite 1 (WS, Post, Post Detail)"
        python -m pytest WS_test.py Post_test.py Post_detail_test.py -n 3 --alluredir=./allure-results || echo "Test suite 1 completed with errors"
        
        echo "Running test suite 2 (Auth, Users, Registration)"
        python -m pytest Auth_test.py Users_test.py registr_test.py --alluredir=./allure-results || echo "Test suite 2 completed with errors"
        
        # Generate Allure report if results exist
        if [ -d "./allure-results" ]; then
          echo "Generating Allure report"
          allure generate ./allure-results -o ./allure-report --clean
          
          # Move report to root directory
          mv ./allure-report ../../allure-report
        else
          echo "No test results found for Allure report"
        fi
        
        # Always succeed to continue workflow
        exit 0

    - name: Upload Allure report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: allure-report
        retention-days: 5

    - name: Cleanup
      run: |
        docker stop django-app || true
        docker rm django-app || true
      if: always()